branches:
  only:
  - master

language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - CMAKE_OPTS = ""
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - CMAKE_OPTS = ""
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - CMAKE_OPTS = "-DCMAKE_BUILD_TYPE=Release"
      before_script:
        - export PATH=$MSBUILD_PATH:$PATH


before_install:
    - cmake --version
    - cd src/shader_suite
    - mkdir build 
    - cd build
    
script:
    - cmake .. ${CMAKE_OPTS}
    - cmake --build .
    
    
 