branches:
  only:
  - master

language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      before_script:
        - export PATH=$MSBUILD_PATH:$PATH


before_install:
    - cmake --version
    #- eval "${MATRIX_EVAL}"
    - cd src/shader_suite
    - mkdir build 
    - cd build
    
script:
    - cmake ..
    - cmake --build .
    
    
 